- name: calatologue installking
  hosts: calatogue
  become: yes
  tasks:
  - name: disble the nodejs 
    ansible.builtin.dnf: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.package:
      name: install nodejs
      state: present
      enabled: yes